# 작업 이름 설정
name: Maven Package 

# 트리거 설정
on: 
  # 새 릴리즈 생성 시
  release:
    types: [created] 
  # 코드가 푸시될 때
  push: 
  # 풀 리퀘스트 생성 시
  pull_request: 

jobs:
  # 빌드 작업
  build: 
    # 운영체제 설정
    runs-on: ubuntu-latest 
    # 권한 설정
    permissions:
      checks: write # 테스트 결과를 publish 하므로 권한 필요
      contents: read
      packages: write

    # 환경 변수 설정
    env: 
      SPRING_DATASOURCE_URL: jdbc:mariadb://localhost:3306/fakestore
      SPRING_DATASOURCE_USERNAME: storeuser
      SPRING_DATASOURCE_PASSWORD: storeuser
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
    # 작업 단계
    steps: 
    # 사용자 정의 네트워크 생성
    - name: Create user-defined network
      run: docker network create my_network 
    # MariaDB 컨테이너 실행
    - name: Run MariaDB container
      run: |
        docker run --name mariadb --network my_network -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=fakestore -e MYSQL_USER=storeuser -e MYSQL_PASSWORD=storeuser -p 3306:3306 -d mariadb:11.0.2 
    # 저장소 체크아웃
    - uses: actions/checkout@v3 
    # JDK 11 설정 -> 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3 
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    # For Debugging
    - name: List all running containers
      run: docker ps # 실행 중인 모든 컨테이너 나열
    # Maven을 사용하여 패키지 빌드
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Ptest 
      
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always() # 이 액션을 항상 실행하도록 설정, 실패한 경우에도
      with:
        files: ./target/surefire-reports/*.xml

